### ISSUE TITLE
加了patch无法加载

### ISSUE THREAD

**Issue by unh3x** [Tools2/Zend-Decoder#2]
自己编译官方的xcache，无问题，php -v可成功加载
打上patch之后，直接无法load了。
PHP Startup: Unable to load dynamic library '/root/xcache/modules/xcache.so' - /root/xcache/modules/xcache.so: undefined symbol: fix_code in Unknown on line 0

写得稍微详细点？
或者留个联系方式交流下？

**Comment by Tools2** [comment]
稍等，今天已经在写详细说明了，晚点会上传编译好的文件。

**Comment by Tools2** [comment]
按照最新说明，或者下载编译好的应该没问题了。

**Comment by asjhwl** [comment]
WINDOWS下编译通过，但OP有垃圾数据。 作者能否留个Q群 或联系方式。

**Comment by Tools2** [comment]
@asjhwl 请提供有垃圾op的php文件
